# Generated by Django 4.0.4 on 2022-05-08 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id_chap', models.AutoField(primary_key=True, serialize=False)),
                ('name_chap', models.CharField(max_length=100)),
                ('ordinal_chap', models.IntegerField()),
                ('date_release', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('GenreID', models.AutoField(primary_key=True, serialize=False)),
                ('Genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.BooleanField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manga.role')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manga.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manga.user')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('chap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manga.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id_comic', models.AutoField(primary_key=True, serialize=False)),
                ('name_comic', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('date_release', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('num_chapter', models.IntegerField()),
                ('views', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manga.genre')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manga.comic'),
        ),
    ]
