# Generated by Django 4.0.4 on 2022-06-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='description',
            field=models.CharField(default='A great manga', max_length=200),
        ),
    ]
