# Generated by Django 4.0.3 on 2022-05-07 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='comic',
            name='genre',
        ),
        migrations.AddField(
            model_name='chapter',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comic',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comic',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='history',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manga.chapter'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manga.user'),
        ),
        migrations.AddField(
            model_name='comic',
            name='genres',
            field=models.ManyToManyField(to='Manga.genre'),
        ),
    ]
