# Generated by Django 4.0.4 on 2022-06-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='index',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
