# Generated by Django 4.0.4 on 2022-06-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0002_alter_chapter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
