# Generated by Django 4.0.4 on 2022-06-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0003_alter_manga_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='thumbnail',
            field=models.CharField(max_length=200),
        ),
    ]
