# Generated by Django 4.0.4 on 2022-06-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanga',
            old_name='chapterId',
            new_name='mangaId',
        ),
    ]
